// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function GetStoredLocale() {
  return window['go']['main']['App']['GetStoredLocale']();
}

export function InstallOrOpenUpdate(arg1) {
  return window['go']['main']['App']['InstallOrOpenUpdate'](arg1);
}

export function OpenExternal(arg1) {
  return window['go']['main']['App']['OpenExternal'](arg1);
}

export function ReadTextFile(arg1) {
  return window['go']['main']['App']['ReadTextFile'](arg1);
}

export function SetStoredLocale(arg1) {
  return window['go']['main']['App']['SetStoredLocale'](arg1);
}
