// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckForUpdates():Promise<void>;

export function GetStoredLocale():Promise<string>;

export function InstallOrOpenUpdate(arg1:main.updateInfo):Promise<void>;

export function OpenExternal(arg1:string):Promise<void>;

export function ReadTextFile(arg1:string):Promise<string>;

export function SetStoredLocale(arg1:string):Promise<string>;
