// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdates():Promise<void>;

export function ReadTextFile(arg1:string):Promise<string>;
